### ISSUE TITLE
Safari on iPhone triggers resize events on scroll

### ISSUE THREAD

**Issue by antgonzales** [antgonzales/decorateText.js#1]
When a user scrolls on the iPhone using Safari, the touch scroll causes a window resize event and alters the text display.

Check out:
https://boagworld.com/dev/ios-safari-resizing-issues/
http://stackoverflow.com/questions/8898412/iphone-ipad-triggering-unexpected-resize-events

**Comment by antgonzales** [comment]
Fixed.

**Comment by bitflower** [comment]
Hey @antgonzales, would you be so kind and let me know how exactly you fixed it? Need a solution for another project.... Thanks!

**Comment by brunob** [comment]
@bitflower fix is there https://github.com/antgonzales/decorateText.js/commit/094ce7af41e6bd37b590205e791e9fd26c4db819

**Comment by antgonzales** [comment]
@bitflower I'm sorry I didn't see your comment previously, is this still an issue?

**Comment by bitflower** [comment]
I think I don't rememebr what I did back then :)

Thanks anyway!
